# Schema for the configuration files of the Search API Synonym module.

search_api_synonym.settings:
  type: config_object
  label: 'Search API Synonym settings'
  mapping:
    cron:
      type: mapping
      label: 'Cron'
      mapping:
        plugin:
          type: string
          label: 'Plugin'
        interval:
          type: integer
          label: 'Interval'
        type:
          type: string
          label: 'Type'
        filter:
          type: string
          label: 'Filter'
        separate_files:
          type: bool
          label: 'Separate files'
        export_if_changed:
          type: bool
          label: 'Export if new added or changed since last export.'
